[package]
name = "anagram-solver-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
log = "0.4.17"
md5 = "0.7.0"

[dev-dependencies]
test-case = "1.2.1"